### ISSUE TITLE
Expected value in Dublin Core: Rights

### ISSUE THREAD

**Issue by adehner** [BGSU-LITS/omeka-plugin-RightsStatements#1]
I'm excited about this plugin, and I'd like to use it, if I'm understanding its output correctly. 

I imagine it expects the presence of a standardized form of either a CC or RS license in the Dublin Core: Rights field. Then, in Omeka's items/show.php, the plugin displays a hyperlinked CC or RS image in place of the text entered in DC:Rights. Is that correct?

If so, I'm not sure what value the plugin is expecting in the Dublin Core: Rights field. I've tried "UND", "Copyright Undetermined", and "http://rightsstatements.org/page/UND/" What should I be entering?

Thanks!!

**Comment by kloor** [comment]
Yes, you're correct about the purpose of the plugin. The value it expects is the URI to the rights statement, and that has to include the version number. So for your example you should use:
`http://rightsstatements.org/page/UND/1.0/`

We went with this format as it was expected by our hub for contribution to the DP.LA. 

Thanks for pointing out the issue, I'll work on adding a README file to the project.

**Comment by adehner** [comment]
Thanks @kloor! 

Upon further inspection, I realized that the Search by Metadata plugin was creating a conflict because it changed the plain text to a hyperlink. 

Thanks again for creating this plugin :)
